language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
    - secure: "XhhrOr48eDHwXKt9P3OgIECqdQZ0mJk+GSYnFcUWKPGd8a3VLwHOcQXMI8DlW4Wd/4RJ52S2SakDwq5YhUktu7YQJZloa/WmT8wFMiuJoMexO5a+zlm3H0IetXIOSUbgrxOHH3T/8hluvB7jCY1BHWvdCgWZXBAxOtkcBbQ/lkY="
    - secure: "H3ap/6ZKbloKjwozHEfJuesPUYm/CQ1uLx7j2eA3TugavGivEfg3/xDG26+/O+kmyJbw7TOZi/dDRXJDT/fyq3lHy997lN2DXXc+8C8b+mmoD2bUUnH074XvR2cbOxy/Mab0vu9D8+tLQGNEpvWujRCSpe62ptUzMQZe9m2Tsis="

script:
- "./gradlew clean test assemble --stacktrace"

after_success:
- "./travis-publish.sh"
